### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by miltonhowe** [Ashark/hliss#3]
The following is missing from the documentation:
* dependencies (`ffmpeg`, `v4l2loopback`)
* precisely which values from `lsusb` need to be added precisely where in `fakecamera`
* it seems to me the following error can be ignored. If so, that should be documented:
`rmmod: ERROR: Module v4l2loopback is not currently loaded`

**Comment by Ashark** [comment]
- Dependencies described in readme.
- Not in fakecamera, but in reinsert-internal-webcam. This stopped working, so I removed it from readme.
- It will not be shown anymore. Do not worry, it could be safely ignored.
Thanks for your interest in this repo.
